# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sungjae Jung
#title: Sungjae Jung
email: sungjae.2425@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username: jungsungjae
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0001-8266-0480
googlescholar_username: Y4bnvrAAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) #(https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
#about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: |
  I specialize in developing cutting-edge technologies for digital healthcare and driving new business opportunities in the field.
  Currently, I lead a research team at Seoul National University and Seoul National University Hospital.
  Our team is focused on the MyData project and the Smart Health Home platform project, leveraging advanced technologies such as Web3 and AI to innovate in digital healthcare.
  Recently, my research has expanded to building and utilizing Knowledge Graphs for Retrieval-Augmented Generation (RAG) in large language models (LLMs), further advancing the application of AI in healthcare solutions.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        border: weak  # Value of `weak` will display a weak border below this item. # Any 
#                      # other value (or no value) means no border will be displayed
#        title: Project name
#        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        link_text: Link Text
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Seoul National University Hospital
        sub_title: Senior Researcher
        caption: Jan 2023 - present
      - layout: left
        title: Seoul National University
        sub_title: Senior Researcher
        caption: Feb 2023 - Sep 2023
      - layout: left
        title: Yonsei University Health System
        sub_title: Researcher
        caption: Aug 2022 - Dec 2022
      - layout: left
        title: Weavrcare (ex. MediBloc)
        sub_title: Researcher
        caption: Dec 2017 - Jul 2020
      - layout: left
        title: Seoul National University Hospital
        sub_title: Researcher
        caption: Nov 2017 - Nov 2017
      - layout: left
        title: Ajou University
        sub_title: Researcher
        caption: Sep 2015 - Oct 2017
      - layout: left
        title: Seoul National University Hospital
        sub_title: Researcher
        caption: Nov 2013 - Aug 2015
      - layout: left
        title: Opensurvey (ex. IDINCU)
        sub_title: Developer
        caption: Mar 2013 - Oct 2013
      - layout: left
        title: Spoqa
        sub_title: Intern
        caption: Jan 2013 - Feb 2013
      - layout: left
        title: Korea Telecom
        sub_title: Intern
        caption: Sep 2012 - Dec 2012
  - title: Education
    layout: list
    content:
      - layout: left
        title: Ajou University
        sub_title: MS Medical Informatics
        caption: Sep 2015 - Aug 2017
      - layout: left
        title: Soongsil University
        sub_title: BE Computer Science and Engineering
        caption: Mar 2007 - Aug 2013
  - title: Projects
    layout: text
    content: | 
      - Mar 2023 - Dec 2025 "Development of HealthCube for Web 3.0 MyData Service" [Github](https://github.com/jungsungjae/healthcube)
      - Jan 2023 - Dec 2023 "Development of Knowledge Base for Smart Health Home Platform"
      - Jul 2022 - Dec 2022 "Development of R packages for Spatio-temporal Epidemiology"
      - Jul 2022 - Dec 2022 "Development of classification model with fine-tuning based on BERT model"
      - Jul 2022 - Jul 2022 "Establishment of research environment based on OMOP CDM"
      - Aug 2020 - Nov 2020 "Performance evaluation of existing ASR(Automatic Speech Recognition) solution using health counseling data"
      - Apr 2020 - Jul 2020 "Development of Blockchain-based personal mobile medical-electronic-documents platform"
      - Oct 2019 - Dec 2019 "Development of a mobile application for personal health record exchanges"
      - Jul 2019 - Dec 2019 "Development of a mobile application for patient alcohol management"
      - May 2019 - Nov 2019 "Development of Blockchain-based forgery monitoring hospital information system"
      - May 2019 - Nov 2019 "Development of Blockchain-based personal health records management platform"
      - Apr 2019 - Jul 2020 "Development of Blockchain platform for health information exchange based on dynamic consent"
      - Oct 2018 - Nov 2018 "Research for integrating PGHD into HL7 FHIR, and use in Blockchain"
      - Aug 2018 - Sep 2018 "Comparison of Data Standards for Personal Health Records"
      - Jul 2018 - Dec 2018 "Proof of Concept for Blockchain-based Medical data sharing on KOREN/TEIN"
      - Jan 2018 - Jun 2018 "Proof of Concept with Seoul National University Hospital"
      - Jan 2017 - May 2017 "Logistic regression of large scale data using distributed processing algorithm"
      - May 2016 - Dec 2016 "Conversion of NHIS Data of Korea to the OMOP Common Data Model"
      - Nov 2015 - Sep 2016 "Development of web based integrated code generating system for cohort analysis"
      - Mar 2016 - Sep 2016 "Development of R packages: CERT, CELAR, SAN, PACE"
      - Sep 2015 - Jun 2016 "Development of tool for visualization of medication data"
      - Sep 2015 - May 2016 "Development of method for detecting adverse drug reaction (ADR) signal"
      - Dec 2014 - Aug 2015 "Initial setup and management of NGS Server"
      - May 2014 - Oct 2014 "Research about Designing Data Warehouse on Korea Association of Health Promotion"
      - Dec 2013 - Mar 2014 "Research about Standardization of reference value of testing clinical specimen"
      - Mar 2013 - Oct 2013 "Development and Quality Assurance of Open Survey"
      - Jan 2013 - Feb 2013 "Development of Operating and Sales Dashboard"
      - Sep 2012 - Dec 2012 "Development of Global Frequency Monitoring System"
      - Apr 2011 - Nov 2011 "Development of Quadcopter (Humming bird)"
  - title: Publications
    layout: text
    content: | 
      - "Developing a Mobile App for Monitoring Medical Record Changes Using Blockchain: Development and Usability Study" [PubMed](https://pubmed.ncbi.nlm.nih.gov/32795988/)
      - "Developing a Mobile App for Patients to Monitor Medical Record Changes Using Blockchain" [PubMed](https://pubmed.ncbi.nlm.nih.gov/32570603/)
      - "Extending Achilles Heel Data Quality Tool with New Rules Informed by Multi-Site Data Quality Comparison" [PubMed](https://pubmed.ncbi.nlm.nih.gov/31438195/)
      - "Comparison of First-Line Dual Combination Treatments in Hypertension: Real-World Evidence from Multinational Heterogeneous Cohorts" [PubMed](https://pubmed.ncbi.nlm.nih.gov/31642211/)
      - "Comparison between first line dual-combination therapies in hypertension: nationwide population based cohort study" [EHJ](https://academic.oup.com/eurheartj/article/38/suppl_1/ehx504.3893/4089616)
      - "Conversion of National Health Insurance Service-National Sample Cohort (NHIS-NSC) Database into Observational Medical Outcomes Partnership-Common Data Model (OMOPCDM)" [PubMed](https://pubmed.ncbi.nlm.nih.gov/29295138/)
      - "The Best Prediction Model for Trauma Outcomes of the Current Korean Population: a Comparative Study of Three Injury Severity Scoring Systems" [ACC](https://www.accjournal.org/journal/view.php?number=1039)
      - "Association between the markers of metabolic acid load and higher all-cause and cardiovascular mortality in a general population with preserved renal function" [PubMed](https://pubmed.ncbi.nlm.nih.gov/25762414/)
  - title: Presentations
    layout: text
    content: | 
      - Poster at MIE 2025, "Development of a Voice-Interactive Chatbot for Personalized Health Management Using a Lifestyle Recommendation Knowledge Base"
      - Poster at ATTD 2025, "EXPLORING FEDERATED LEARNING FOR SECURE HEALTH DATA UTILIZATION ON PERSONAL DEVICES"
      - Poster at HEALTHINF 2025, "Architectural Design for a Web3-Based Healthcare System Associated with the MyHealthWay Platform in the Republic of Korea"
      - Poster at OHDSI Symposium 2017, "A regression analysis method for distributed large-scale data analysis"
      - Poster at OHDSI Symposium 2016, "A web based integrated code generating system for cohort analysis"
      - Poster at OHDSI Symposium 2016, "Conversion of National Health Insurance Service (NHIS) Data of Korea to the Observational Medical Outcomes Partnership (OMOP) Common Data Model"
      - Poster at OHDSI Symposium 2016, "AURORA: analytic code managing and distributing tool between researchers and data partners"
      - Poster at KOSMI 2016 Spring, "A code generating system for cohort analysis based on web apps"
  - title: Patents
    layout: text
    content: | 
      - "System and Method for the analysis of large amount of data"
      - "Wireless charging method and system in a Wi-Fi zone"

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
